spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/booklendingsystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages
  web:
    locale: zh-CN
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

resources:
      static-locations: classpath:/templates/,classpath:/static/
file:
  upload-dir: E:\Desktop\book1\src\main\resources\static\uploads
